services:
  - type: web
    name: banco-digital-flask
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_database.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      # Descomente as linhas abaixo se quiser usar PostgreSQL
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: banco-digital-db
      #     property: connectionString

# Descomente o bloco abaixo se quiser criar um banco PostgreSQL
# databases:
#   - name: banco-digital-db
#     databaseName: bancodigital
#     user: bancodigital
